version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MEMORY_LIMIT=4g
      - DRIVER_MEMORY=2g
    volumes:
      - ./saved_model:/app/saved_model
