services:
  - type: web
    name: used-car-price-predictor-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    branches: [main]
    autoDeploy: true
